p={}
print("datatype=",type(p))
s=set(p)
print("datatype=",type(s))
s.add(1)
s.add(2)
s.add(3)
print("the set is=",s)
s.discard(3)
s.remove(2)
s.add(5)
s.add(6)
print("the new set is=",s)
s.update({1,8,7,9,2,3,5},{5,6,47,8})
print("the update set is=",s)
s1=set()
s1.add(2)
s1.add(3)
s1.add(5)
print("the new set is=",s1)
i=s1.intersection(s)
print("the intersection of the sets are=",i)
u=s.union(s1)
print("the union of the sets are",u)
print("if s1 is subset of s",s1.issubset(s))
print("if s is superset of s1",s.issuperset(s1))

