date=input("enter your date=")
day,month,year=date.split("/")
print("day=",day)
print("month=",month)
print("year=",year)
d=input("enter new dob=")
z=d.replace("/",".")
DAY,MONTH,YEAR=z.split(".")
print("day=",DAY)
print("month=",MONTH)
print("year=",YEAR)